<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE examples [
<!ELEMENT examples (example*)>
<!ELEMENT example (nl*,mrl*,mrl-parse?)>
<!ELEMENT nl (#PCDATA)>
<!ELEMENT mrl (#PCDATA)>
<!ELEMENT mrl-parse (node*)>
<!ELEMENT node (#PCDATA)>
]>
<examples>

 <example id='1'>
  <nl lang='en'> virginia </nl>
  <nl lang='es'> virginia </nl>
  <nl lang='ja'> baajinia </nl>
  <nl lang='tr'> virginia </nl>
  <nl lang='el'> virginia </nl>
  <nl lang='de'> virginia </nl>
  <nl lang='th'> เวอร์จิเนีย </nl>
  <nl lang='zh'> 弗吉尼亚 </nl>
  <mrl lang='geo-funql'> ' virginia ' </mrl>
  <mrl lang='geo-prolog'>  </mrl>
  <mrl-parse>
   <node id='0'> *n:StateName -> ({ ' virginia ' }) </node>
  </mrl-parse>
 </example>

 <example id='2'>
  <nl lang='en'> mississippi </nl>
  <nl lang='es'> mississippi </nl>
  <nl lang='ja'> mishishippi </nl>
  <nl lang='tr'> mississippi </nl>
  <nl lang='el'> mississippi </nl>
  <nl lang='de'> mississippi </nl>
  <nl lang='th'> มิสซิสซิปปี </nl>
  <nl lang='zh'> 密西西比 </nl>
  <mrl lang='geo-funql'> ' mississippi ' </mrl>
  <mrl lang='geo-prolog'>  </mrl>
  <mrl-parse>
   <node id='0'> *n:StateName -> ({ ' mississippi ' }) </node>
  </mrl-parse>
 </example>

 <example id='3'>
  <nl lang='en'> arkansas </nl>
  <nl lang='es'> arkansas </nl>
  <nl lang='ja'> aakansaa </nl>
  <nl lang='tr'> arkansas </nl>
  <nl lang='el'> arkansas </nl>
  <nl lang='de'> arkansas </nl>
  <nl lang='th'> อาร์คันซอ </nl>
  <nl lang='zh'> 阿肯色 </nl>
  <mrl lang='geo-funql'> ' arkansas ' </mrl>
  <mrl lang='geo-prolog'>  </mrl>
  <mrl-parse>
   <node id='0'> *n:StateName -> ({ ' arkansas ' }) </node>
  </mrl-parse>
 </example>

 <example id='4'>
  <nl lang='en'> colorado </nl>
  <nl lang='es'> colorado </nl>
  <nl lang='ja'> kororado </nl>
  <nl lang='tr'> colorado </nl>
  <nl lang='el'> colorado </nl>
  <nl lang='de'> colorado </nl>
  <nl lang='th'> โคโลราโด </nl>
  <nl lang='zh'> 科罗拉多 </nl>
  <mrl lang='geo-funql'> ' colorado ' </mrl>
  <mrl lang='geo-prolog'>  </mrl>
  <mrl-parse>
   <node id='0'> *n:StateName -> ({ ' colorado ' }) </node>
  </mrl-parse>
 </example>

 <example id='5'>
  <nl lang='en'> texas </nl>
  <nl lang='es'> texas </nl>
  <nl lang='ja'> tekisasu </nl>
  <nl lang='tr'> texas </nl>
  <nl lang='el'> texas </nl>
  <nl lang='de'> texas </nl>
  <nl lang='de'> texanische </nl>
  <nl lang='th'> เท็กซัส </nl>
  <nl lang='zh'> 德克萨斯 </nl>
  <nl lang='zh'> 德 </nl>
  <mrl lang='geo-funql'> ' texas ' </mrl>
  <mrl lang='geo-prolog'>  </mrl>
  <mrl-parse>
   <node id='0'> *n:StateName -> ({ ' texas ' }) </node>
  </mrl-parse>
 </example>

 <example id='6'>
  <nl lang='en'> oregon </nl>
  <nl lang='es'> oregon </nl>
  <nl lang='ja'> oregon </nl>
  <nl lang='tr'> oregon </nl>
  <nl lang='el'> oregon </nl>
  <nl lang='de'> oregon </nl>
  <nl lang='th'> โอเรกอน </nl>
  <nl lang='zh'> 俄勒冈 </nl>
  <mrl lang='geo-funql'> ' oregon ' </mrl>
  <mrl lang='geo-prolog'>  </mrl>
  <mrl-parse>
   <node id='0'> *n:StateName -> ({ ' oregon ' }) </node>
  </mrl-parse>
 </example>

 <example id='7'>
  <nl lang='en'> alabama </nl>
  <nl lang='es'> alabama </nl>
  <nl lang='ja'> arabama </nl>
  <nl lang='tr'> alabama </nl>
  <nl lang='el'> alabama </nl>
  <nl lang='el'> αλαμπάμα </nl>
  <nl lang='de'> alabama </nl>
  <nl lang='th'> อลาบามา </nl>
  <nl lang='zh'> 阿拉巴马 </nl>
  <mrl lang='geo-funql'> ' alabama ' </mrl>
  <mrl lang='geo-prolog'>  </mrl>
  <mrl-parse>
   <node id='0'> *n:StateName -> ({ ' alabama ' }) </node>
  </mrl-parse>
 </example>

 <example id='8'>
  <nl lang='en'> usa </nl>
  <nl lang='en'> us </nl>
  <nl lang='en'> america </nl>
  <nl lang='en'> united states </nl>
  <nl lang='en'> country </nl>
  <nl lang='es'> america </nl>
  <nl lang='es'> usa </nl>
  <nl lang='es'> us </nl>
  <nl lang='es'> el pais </nl>
  <nl lang='es'> united states </nl>
  <nl lang='ja'> amerika </nl>
  <nl lang='ja'> beikoku </nl>
  <nl lang='ja'> kuni </nl>
  <nl lang='tr'> amerika </nl>
  <nl lang='tr'> usa </nl>
  <nl lang='tr'> us </nl>
  <nl lang='tr'> ulke </nl>
  <nl lang='tr'> birlesik devletler </nl>
  <nl lang='el'> ηπα </nl>
  <nl lang='el'> αμερική </nl>
  <nl lang='el'> usa </nl>
  <nl lang='el'> ηνωμένες πολιτείες </nl>
  <nl lang='el'> us </nl>
  <nl lang='el'> χώρα </nl>
  <nl lang='de'> usa </nl>
  <nl lang='de'> amerika </nl>
  <nl lang='de'> vereinigten staaten </nl>
  <nl lang='de'> us </nl>
  <nl lang='de'> dem land </nl>
  <nl lang='th'> สหรัฐ </nl>
  <nl lang='th'> อเมริกา </nl>
  <nl lang='th'> สหรัฐอเมริกา </nl>
  <nl lang='th'> ประเทศ อเมริกา </nl>
  <nl lang='th'> แผ่นดิน อเมริกา </nl>
  <nl lang='th'> ประเทศ สหรัฐอเมริกา </nl>
  <nl lang='th'> ประเทศ </nl>
  <nl lang='zh'> 这个 国家 </nl>
  <nl lang='zh'> 美国 </nl>
  <mrl lang='geo-funql'> ' usa ' </mrl>
  <mrl lang='geo-prolog'>  </mrl>
  <mrl-parse>
   <node id='0'> *n:CountryName -> ({ ' usa ' }) </node>
  </mrl-parse>
 </example>

 <example id='9'>
  <nl lang='en'> california </nl>
  <nl lang='es'> california </nl>
  <nl lang='ja'> karifuorunia </nl>
  <nl lang='tr'> california </nl>
  <nl lang='el'> california </nl>
  <nl lang='de'> california </nl>
  <nl lang='de'> kaliforniens </nl>
  <nl lang='de'> kalifornien </nl>
  <nl lang='th'> แคลิฟอร์เนีย </nl>
  <nl lang='zh'> 加 </nl>
  <nl lang='zh'> 加利福尼亚 </nl>
  <mrl lang='geo-funql'> ' california ' </mrl>
  <mrl lang='geo-prolog'>  </mrl>
  <mrl-parse>
   <node id='0'> *n:StateName -> ({ ' california ' }) </node>
  </mrl-parse>
 </example>

 <example id='10'>
  <nl lang='en'> utah </nl>
  <nl lang='es'> utah </nl>
  <nl lang='ja'> yuutaa </nl>
  <nl lang='tr'> utah </nl>
  <nl lang='el'> utah </nl>
  <nl lang='de'> utah </nl>
  <nl lang='th'> ยูทาห์ </nl>
  <nl lang='zh'> 犹他 </nl>
  <mrl lang='geo-funql'> ' utah ' </mrl>
  <mrl lang='geo-prolog'>  </mrl>
  <mrl-parse>
   <node id='0'> *n:StateName -> ({ ' utah ' }) </node>
  </mrl-parse>
 </example>

 <example id='11'>
  <nl lang='en'> alaska </nl>
  <nl lang='es'> alaska </nl>
  <nl lang='ja'> arasuka </nl>
  <nl lang='tr'> alaska </nl>
  <nl lang='el'> alaska </nl>
  <nl lang='de'> alaska </nl>
  <nl lang='th'> อลาสกา </nl>
  <nl lang='th'> อลาสก้า </nl>
  <nl lang='zh'> 阿拉斯加 </nl>
  <mrl lang='geo-funql'> ' alaska ' </mrl>
  <mrl lang='geo-prolog'>  </mrl>
  <mrl-parse>
   <node id='0'> *n:StateName -> ({ ' alaska ' }) </node>
  </mrl-parse>
 </example>

 <example id='12'>
  <nl lang='en'> massachusetts </nl>
  <nl lang='es'> massachusetts </nl>
  <nl lang='ja'> masachuusettsu </nl>
  <nl lang='tr'> massachusetts </nl>
  <nl lang='el'> massachusetts </nl>
  <nl lang='de'> massachusetts </nl>
  <nl lang='th'> แมสซาชูเซ็ต </nl>
  <nl lang='th'> แมสซาชูเซ็ตต์ </nl>
  <nl lang='zh'> 马萨诸塞 </nl>
  <mrl lang='geo-funql'> ' massachusetts ' </mrl>
  <mrl lang='geo-prolog'>  </mrl>
  <mrl-parse>
   <node id='0'> *n:StateName -> ({ ' massachusetts ' }) </node>
  </mrl-parse>
 </example>

 <example id='13'>
  <nl lang='en'> new mexico </nl>
  <nl lang='es'> new mexico </nl>
  <nl lang='ja'> nyuu mekishiko </nl>
  <nl lang='tr'> new mexico </nl>
  <nl lang='el'> new mexico </nl>
  <nl lang='de'> new mexico </nl>
  <nl lang='de'> neu mexiko </nl>
  <nl lang='th'> นิวเม็กซิโก </nl>
  <nl lang='zh'> 新墨西哥 </nl>
  <mrl lang='geo-funql'> ' new mexico ' </mrl>
  <mrl lang='geo-prolog'>  </mrl>
  <mrl-parse>
   <node id='0'> *n:StateName -> ({ ' new mexico ' }) </node>
  </mrl-parse>
 </example>

 <example id='14'>
  <nl lang='en'> north dakota </nl>
  <nl lang='es'> north dakota </nl>
  <nl lang='ja'> noosu dakota </nl>
  <nl lang='tr'> north dakota </nl>
  <nl lang='el'> north dakota </nl>
  <nl lang='de'> north dakota </nl>
  <nl lang='th'> นอร์ธดาโกต้า </nl>
  <nl lang='th'> นอร์ธดาโกตา </nl>
  <nl lang='zh'> 北达科他 </nl>
  <mrl lang='geo-funql'> ' north dakota ' </mrl>
  <mrl lang='geo-prolog'>  </mrl>
  <mrl-parse>
   <node id='0'> *n:StateName -> ({ ' north dakota ' }) </node>
  </mrl-parse>
 </example>

 <example id='15'>
  <nl lang='en'> new york </nl>
  <nl lang='es'> new york </nl>
  <nl lang='ja'> nyuu yooku </nl>
  <nl lang='tr'> new york sehrinin </nl>
  <nl lang='el'> new york </nl>
  <nl lang='de'> stadt new york </nl>
  <nl lang='de'> new york city </nl>
  <nl lang='th'> นิวยอร์ค </nl>
  <nl lang='zh'> 纽约 </nl>
  <mrl lang='geo-funql'> ' new york ' </mrl>
  <mrl lang='geo-prolog'>  </mrl>
  <mrl-parse>
   <node id='0'> *n:CityName -> ({ ' new york ' }) </node>
  </mrl-parse>
 </example>

 <example id='16'>
  <nl lang='en'> guadalupe peak </nl>
  <nl lang='el'> κορυφή guadalupe </nl>
  <nl lang='de'> guadalupe peak </nl>
  <nl lang='th'> ยอดเขา กวาดาลูเป </nl>
  <nl lang='zh'> 瓜峰 </nl>
  <mrl lang='geo-funql'> ' guadalupe peak ' </mrl>
  <mrl lang='geo-prolog'>  </mrl>
  <mrl-parse>
   <node id='0'> *n:PlaceName -> ({ ' guadalupe peak ' }) </node>
  </mrl-parse>
 </example>

 <example id='17'>
  <nl lang='en'> mount mckinley </nl>
  <nl lang='el'> όρος mckinley </nl>
  <nl lang='el'> όρους mckinley </nl>
  <nl lang='de'> mount mckinley </nl>
  <nl lang='th'> ยอดเขา แมคคินลีย์ </nl>
  <nl lang='th'> ภูเขา แมคคินลีย์ </nl>
  <nl lang='th'> ภูเขา แม็คคินลีย์ </nl>
  <nl lang='zh'> 麦金利 山 </nl>
  <mrl lang='geo-funql'> ' mount mckinley ' </mrl>
  <mrl lang='geo-prolog'>  </mrl>
  <mrl-parse>
   <node id='0'> *n:PlaceName -> ({ ' mount mckinley ' }) </node>
  </mrl-parse>
 </example>

 <example id='18'>
  <nl lang='en'> montana </nl>
  <nl lang='es'> montana </nl>
  <nl lang='ja'> montana </nl>
  <nl lang='tr'> montana </nl>
  <nl lang='el'> montana </nl>
  <nl lang='de'> montana </nl>
  <nl lang='de'> montanas </nl>
  <nl lang='th'> มอนตานา </nl>
  <nl lang='th'> มอนตาน่า </nl>
  <nl lang='zh'> 蒙大拿 </nl>
  <mrl lang='geo-funql'> ' montana ' </mrl>
  <mrl lang='geo-prolog'>  </mrl>
  <mrl-parse>
   <node id='0'> *n:StateName -> ({ ' montana ' }) </node>
  </mrl-parse>
 </example>

 <example id='19'>
  <nl lang='en'> delaware </nl>
  <nl lang='es'> delaware </nl>
  <nl lang='ja'> derawaru </nl>
  <nl lang='tr'> delaware </nl>
  <nl lang='el'> delaware </nl>
  <nl lang='de'> delaware </nl>
  <nl lang='th'> เดลาแวร์ </nl>
  <nl lang='zh'> 特拉华 </nl>
  <mrl lang='geo-funql'> ' delaware ' </mrl>
  <mrl lang='geo-prolog'>  </mrl>
  <mrl-parse>
   <node id='0'> *n:StateName -> ({ ' delaware ' }) </node>
  </mrl-parse>
 </example>

 <example id='20'>
  <nl lang='en'> florida </nl>
  <nl lang='es'> florida </nl>
  <nl lang='ja'> furorida </nl>
  <nl lang='tr'> florida </nl>
  <nl lang='el'> florida </nl>
  <nl lang='de'> floridas </nl>
  <nl lang='de'> florida </nl>
  <nl lang='de'> florida state </nl>
  <nl lang='th'> ฟลอริด้า </nl>
  <nl lang='th'> ฟลอริดา </nl>
  <nl lang='zh'> 佛罗里达 </nl>
  <mrl lang='geo-funql'> ' florida ' </mrl>
  <mrl lang='geo-prolog'>  </mrl>
  <mrl-parse>
   <node id='0'> *n:StateName -> ({ ' florida ' }) </node>
  </mrl-parse>
 </example>

 <example id='21'>
  <nl lang='en'> louisiana </nl>
  <nl lang='es'> louisiana </nl>
  <nl lang='ja'> ruijiana </nl>
  <nl lang='tr'> louisiana </nl>
  <nl lang='el'> louisiana </nl>
  <nl lang='de'> louisiana </nl>
  <nl lang='th'> หลุยเซียนา </nl>
  <nl lang='zh'> 路易斯安那 </nl>
  <mrl lang='geo-funql'> ' louisiana ' </mrl>
  <mrl lang='geo-prolog'>  </mrl>
  <mrl-parse>
   <node id='0'> *n:StateName -> ({ ' louisiana ' }) </node>
  </mrl-parse>
 </example>

 <example id='22'>
  <nl lang='en'> rio grande </nl>
  <nl lang='es'> rio grande </nl>
  <nl lang='ja'> rio gurande </nl>
  <nl lang='tr'> rio grande </nl>
  <nl lang='el'> rio grande </nl>
  <nl lang='de'> rio grande </nl>
  <nl lang='th'> ริโอแกรนด์ </nl>
  <nl lang='zh'> 里奥格兰德 </nl>
  <nl lang='zh'> 格兰德 </nl>
  <mrl lang='geo-funql'> ' rio grande ' </mrl>
  <mrl lang='geo-prolog'>  </mrl>
  <mrl-parse>
   <node id='0'> *n:RiverName -> ({ ' rio grande ' }) </node>
  </mrl-parse>
 </example>

 <example id='23'>
  <nl lang='en'> colorado </nl>
  <nl lang='es'> colorado </nl>
  <nl lang='ja'> kororado </nl>
  <nl lang='tr'> colorado </nl>
  <nl lang='el'> colorado </nl>
  <nl lang='de'> colorado </nl>
  <nl lang='th'> โคโลราโด </nl>
  <nl lang='zh'> 科罗拉多 </nl>
  <mrl lang='geo-funql'> ' colorado ' </mrl>
  <mrl lang='geo-prolog'>  </mrl>
  <mrl-parse>
   <node id='0'> *n:RiverName -> ({ ' colorado ' }) </node>
  </mrl-parse>
 </example>

 <example id='24'>
  <nl lang='en'> delaware </nl>
  <nl lang='es'> delaware </nl>
  <nl lang='ja'> derawaru </nl>
  <nl lang='tr'> delaware </nl>
  <nl lang='el'> delaware </nl>
  <nl lang='de'> delaware </nl>
  <nl lang='th'> เดลาแวร์ </nl>
  <nl lang='zh'> 特拉华 </nl>
  <mrl lang='geo-funql'> ' delaware ' </mrl>
  <mrl lang='geo-prolog'>  </mrl>
  <mrl-parse>
   <node id='0'> *n:RiverName -> ({ ' delaware ' }) </node>
  </mrl-parse>
 </example>

 <example id='25'>
  <nl lang='en'> mississippi </nl>
  <nl lang='es'> mississippi </nl>
  <nl lang='ja'> mishishippi </nl>
  <nl lang='tr'> mississippi </nl>
  <nl lang='el'> mississippi </nl>
  <nl lang='de'> mississippi </nl>
  <nl lang='th'> มิสซิสซิปปี </nl>
  <nl lang='zh'> 密西西比 </nl>
  <mrl lang='geo-funql'> ' mississippi ' </mrl>
  <mrl lang='geo-prolog'>  </mrl>
  <mrl-parse>
   <node id='0'> *n:RiverName -> ({ ' mississippi ' }) </node>
  </mrl-parse>
 </example>

 <example id='26'>
  <nl lang='en'> missouri </nl>
  <nl lang='es'> missouri </nl>
  <nl lang='ja'> mizuuri </nl>
  <nl lang='tr'> missouri </nl>
  <nl lang='el'> missouri </nl>
  <nl lang='de'> missouri </nl>
  <nl lang='th'> มิสซูรี </nl>
  <nl lang='th'> มิสซูรี่ </nl>
  <nl lang='zh'> 密苏里 </nl>
  <mrl lang='geo-funql'> ' missouri ' </mrl>
  <mrl lang='geo-prolog'>  </mrl>
  <mrl-parse>
   <node id='0'> *n:RiverName -> ({ ' missouri ' }) </node>
  </mrl-parse>
 </example>

 <example id='27'>
  <nl lang='en'> north platte </nl>
  <nl lang='es'> north platte </nl>
  <nl lang='ja'> noosu puratte </nl>
  <nl lang='tr'> north platte </nl>
  <nl lang='el'> βόρειος platte </nl>
  <nl lang='de'> north platte </nl>
  <nl lang='th'> นอร์ธเพลต </nl>
  <nl lang='zh'> 北普拉特 </nl>
  <mrl lang='geo-funql'> ' north platte ' </mrl>
  <mrl lang='geo-prolog'>  </mrl>
  <mrl-parse>
   <node id='0'> *n:RiverName -> ({ ' north platte ' }) </node>
  </mrl-parse>
 </example>

 <example id='28'>
  <nl lang='en'> ohio </nl>
  <nl lang='es'> ohio </nl>
  <nl lang='ja'> ohaio </nl>
  <nl lang='tr'> ohio </nl>
  <nl lang='el'> ohio </nl>
  <nl lang='de'> ohio </nl>
  <nl lang='th'> โอไฮโฮ </nl>
  <nl lang='th'> โอไฮโอ </nl>
  <nl lang='zh'> 俄亥俄 </nl>
  <mrl lang='geo-funql'> ' ohio ' </mrl>
  <mrl lang='geo-prolog'>  </mrl>
  <mrl-parse>
   <node id='0'> *n:RiverName -> ({ ' ohio ' }) </node>
  </mrl-parse>
 </example>

 <example id='29'>
  <nl lang='en'> pennsylvania </nl>
  <nl lang='el'> pennsylvania </nl>
  <nl lang='de'> pennsylvania </nl>
  <nl lang='th'> เพ็นซิลเวเนีย </nl>
  <nl lang='th'> เพนซิลเวเนีย </nl>
  <nl lang='zh'> 宾夕法尼亚 </nl>
  <mrl lang='geo-funql'> ' pennsylvania ' </mrl>
  <mrl lang='geo-prolog'>  </mrl>
  <mrl-parse>
   <node id='0'> *n:StateName -> ({ ' pennsylvania ' }) </node>
  </mrl-parse>
 </example>

 <example id='30'>
  <nl lang='en'> rhode island </nl>
  <nl lang='es'> rhode island </nl>
  <nl lang='ja'> roodoairando </nl>
  <nl lang='tr'> rhode island </nl>
  <nl lang='el'> rhode island </nl>
  <nl lang='de'> rhode island </nl>
  <nl lang='th'> โรดไอแลนด์ </nl>
  <nl lang='zh'> 罗得岛 </nl>
  <mrl lang='geo-funql'> ' rhode island ' </mrl>
  <mrl lang='geo-prolog'>  </mrl>
  <mrl-parse>
   <node id='0'> *n:StateName -> ({ ' rhode island ' }) </node>
  </mrl-parse>
 </example>

 <example id='31'>
  <nl lang='en'> austin </nl>
  <nl lang='es'> austin </nl>
  <nl lang='ja'> ausuchin </nl>
  <nl lang='tr'> austin </nl>
  <nl lang='el'> austin </nl>
  <nl lang='de'> austin </nl>
  <nl lang='th'> ออสติน </nl>
  <nl lang='zh'> 奥斯汀 </nl>
  <mrl lang='geo-funql'> ' austin ' </mrl>
  <mrl lang='geo-prolog'>  </mrl>
  <mrl-parse>
   <node id='0'> *n:CityName -> ({ ' austin ' }) </node>
  </mrl-parse>
 </example>

 <example id='32'>
  <nl lang='en'> boulder </nl>
  <nl lang='el'> boulder </nl>
  <nl lang='de'> boulder </nl>
  <nl lang='th'> โบลเดอร์ </nl>
  <nl lang='zh'> 博尔德 </nl>
  <mrl lang='geo-funql'> ' boulder ' </mrl>
  <mrl lang='geo-prolog'>  </mrl>
  <mrl-parse>
   <node id='0'> *n:CityName -> ({ ' boulder ' }) </node>
  </mrl-parse>
 </example>

 <example id='33'>
  <nl lang='en'> montgomery </nl>
  <nl lang='el'> montgomery </nl>
  <nl lang='de'> montgomery </nl>
  <nl lang='th'> มอนต์โกเมอรี </nl>
  <nl lang='zh'> 蒙哥马利 </nl>
  <mrl lang='geo-funql'> ' montgomery ' </mrl>
  <mrl lang='geo-prolog'>  </mrl>
  <mrl-parse>
   <node id='0'> *n:CityName -> ({ ' montgomery ' }) </node>
  </mrl-parse>
 </example>

 <example id='34'>
  <nl lang='en'> arizona </nl>
  <nl lang='es'> arizona </nl>
  <nl lang='ja'> arizona </nl>
  <nl lang='tr'> arizona </nl>
  <nl lang='el'> arizona </nl>
  <nl lang='de'> arizona </nl>
  <nl lang='th'> แอริโซนา </nl>
  <nl lang='zh'> 亚利桑那 </nl>
  <mrl lang='geo-funql'> ' arizona ' </mrl>
  <mrl lang='geo-prolog'>  </mrl>
  <mrl-parse>
   <node id='0'> *n:StateName -> ({ ' arizona ' }) </node>
  </mrl-parse>
 </example>

 <example id='35'>
  <nl lang='en'> nebraska </nl>
  <nl lang='es'> nebraska </nl>
  <nl lang='ja'> neburasuka </nl>
  <nl lang='tr'> nebraska </nl>
  <nl lang='el'> nebraska </nl>
  <nl lang='de'> nebraska </nl>
  <nl lang='th'> เนบราสกา </nl>
  <nl lang='th'> เนบราสก้า </nl>
  <nl lang='zh'> 内布拉斯加 </nl>
  <mrl lang='geo-funql'> ' nebraska ' </mrl>
  <mrl lang='geo-prolog'>  </mrl>
  <mrl-parse>
   <node id='0'> *n:StateName -> ({ ' nebraska ' }) </node>
  </mrl-parse>
 </example>

 <example id='36'>
  <nl lang='en'> ohio </nl>
  <nl lang='es'> ohio </nl>
  <nl lang='ja'> ohaio </nl>
  <nl lang='tr'> ohio </nl>
  <nl lang='el'> ohio </nl>
  <nl lang='de'> ohio </nl>
  <nl lang='th'> โอไฮโอ </nl>
  <nl lang='th'> โอไฮโฮ </nl>
  <nl lang='zh'> 俄亥俄 </nl>
  <mrl lang='geo-funql'> ' ohio ' </mrl>
  <mrl lang='geo-prolog'>  </mrl>
  <mrl-parse>
   <node id='0'> *n:StateName -> ({ ' ohio ' }) </node>
  </mrl-parse>
 </example>

 <example id='37'>
  <nl lang='en'> nevada </nl>
  <nl lang='es'> nevada </nl>
  <nl lang='ja'> nebaada </nl>
  <nl lang='tr'> nevada </nl>
  <nl lang='el'> nevada </nl>
  <nl lang='de'> nevada </nl>
  <nl lang='th'> เนวาดา </nl>
  <nl lang='zh'> 内华达 </nl>
  <mrl lang='geo-funql'> ' nevada ' </mrl>
  <mrl lang='geo-prolog'>  </mrl>
  <mrl-parse>
   <node id='0'> *n:StateName -> ({ ' nevada ' }) </node>
  </mrl-parse>
 </example>

 <example id='38'>
  <nl lang='en'> iowa </nl>
  <nl lang='es'> iowa </nl>
  <nl lang='ja'> aiowa </nl>
  <nl lang='tr'> iowa </nl>
  <nl lang='el'> iowa </nl>
  <nl lang='de'> iowa </nl>
  <nl lang='th'> ไอโอวา </nl>
  <nl lang='zh'> 爱荷华 </nl>
  <nl lang='zh'> 艾奥瓦 </nl>
  <mrl lang='geo-funql'> ' iowa ' </mrl>
  <mrl lang='geo-prolog'>  </mrl>
  <mrl-parse>
   <node id='0'> *n:StateName -> ({ ' iowa ' }) </node>
  </mrl-parse>
 </example>

 <example id='39'>
  <nl lang='en'> new york </nl>
  <nl lang='es'> new york </nl>
  <nl lang='ja'> nyuu yooku </nl>
  <nl lang='tr'> new york </nl>
  <nl lang='el'> new york </nl>
  <nl lang='de'> new york </nl>
  <nl lang='de'> new yorks </nl>
  <nl lang='th'> นิวยอร์ค </nl>
  <nl lang='zh'> 纽约 </nl>
  <mrl lang='geo-funql'> ' new york ' </mrl>
  <mrl lang='geo-prolog'>  </mrl>
  <mrl-parse>
   <node id='0'> *n:StateName -> ({ ' new york ' }) </node>
  </mrl-parse>
 </example>

 <example id='40'>
  <nl lang='en'> texas </nl>
  <nl lang='el'> texas </nl>
  <nl lang='de'> texas </nl>
  <nl lang='th'> เท็กซัส </nl>
  <nl lang='zh'> 得克萨斯 </nl>
  <mrl lang='geo-funql'> ' tx ' </mrl>
  <mrl lang='geo-prolog'>  </mrl>
  <mrl-parse>
   <node id='0'> *n:StateAbbrev -> ({ ' tx ' }) </node>
  </mrl-parse>
 </example>

 <example id='41'>
  <nl lang='en'> chicago </nl>
  <nl lang='el'> chicago </nl>
  <nl lang='de'> chicago </nl>
  <nl lang='th'> ชิคาโก </nl>
  <nl lang='zh'> 芝加哥 </nl>
  <mrl lang='geo-funql'> ' chicago ' </mrl>
  <mrl lang='geo-prolog'>  </mrl>
  <mrl-parse>
   <node id='0'> *n:CityName -> ({ ' chicago ' }) </node>
  </mrl-parse>
 </example>

 <example id='42'>
  <nl lang='en'> detroit </nl>
  <nl lang='el'> detroit </nl>
  <nl lang='de'> detroit </nl>
  <nl lang='th'> ดีทรอยท์ </nl>
  <nl lang='zh'> 底特律 </nl>
  <mrl lang='geo-funql'> ' detroit ' </mrl>
  <mrl lang='geo-prolog'>  </mrl>
  <mrl-parse>
   <node id='0'> *n:CityName -> ({ ' detroit ' }) </node>
  </mrl-parse>
 </example>

 <example id='43'>
  <nl lang='en'> hawaii </nl>
  <nl lang='es'> hawaii </nl>
  <nl lang='ja'> hawai </nl>
  <nl lang='tr'> hawaii </nl>
  <nl lang='el'> hawaii </nl>
  <nl lang='de'> hawaii </nl>
  <nl lang='th'> ฮาวาย </nl>
  <nl lang='zh'> 夏威夷 </nl>
  <mrl lang='geo-funql'> ' hawaii ' </mrl>
  <mrl lang='geo-prolog'>  </mrl>
  <mrl-parse>
   <node id='0'> *n:StateName -> ({ ' hawaii ' }) </node>
  </mrl-parse>
 </example>

 <example id='44'>
  <nl lang='en'> houston </nl>
  <nl lang='el'> houston </nl>
  <nl lang='de'> houston </nl>
  <nl lang='th'> ฮุสตัน </nl>
  <nl lang='zh'> 休斯敦 </nl>
  <mrl lang='geo-funql'> ' houston ' </mrl>
  <mrl lang='geo-prolog'>  </mrl>
  <mrl-parse>
   <node id='0'> *n:CityName -> ({ ' houston ' }) </node>
  </mrl-parse>
 </example>

 <example id='45'>
  <nl lang='en'> kalamazoo </nl>
  <nl lang='es'> kalamazoo </nl>
  <nl lang='ja'> karamazuu </nl>
  <nl lang='tr'> kalamazoo </nl>
  <nl lang='el'> kalamazoo </nl>
  <nl lang='de'> kalamazoo </nl>
  <nl lang='th'> คาลามาซู </nl>
  <nl lang='zh'> 卡拉马祖 </nl>
  <mrl lang='geo-funql'> ' kalamazoo ' </mrl>
  <mrl lang='geo-prolog'>  </mrl>
  <mrl-parse>
   <node id='0'> *n:CityName -> ({ ' kalamazoo ' }) </node>
  </mrl-parse>
 </example>

 <example id='46'>
  <nl lang='en'> kansas </nl>
  <nl lang='es'> kansas </nl>
  <nl lang='ja'> kanzasu </nl>
  <nl lang='tr'> kansas </nl>
  <nl lang='el'> kansas </nl>
  <nl lang='de'> kansas </nl>
  <nl lang='th'> แคนซัส </nl>
  <nl lang='zh'> 堪萨斯 </nl>
  <mrl lang='geo-funql'> ' kansas ' </mrl>
  <mrl lang='geo-prolog'>  </mrl>
  <mrl-parse>
   <node id='0'> *n:StateName -> ({ ' kansas ' }) </node>
  </mrl-parse>
 </example>

 <example id='47'>
  <nl lang='en'> minneapolis </nl>
  <nl lang='es'> minneapolis </nl>
  <nl lang='ja'> mineaporisu </nl>
  <nl lang='tr'> minneapolis </nl>
  <nl lang='el'> minneapolis </nl>
  <nl lang='de'> minneapolis </nl>
  <nl lang='th'> มินเนอาโพลิส </nl>
  <nl lang='zh'> 明尼阿波利斯 </nl>
  <mrl lang='geo-funql'> ' minneapolis ' </mrl>
  <mrl lang='geo-prolog'>  </mrl>
  <mrl-parse>
   <node id='0'> *n:CityName -> ({ ' minneapolis ' }) </node>
  </mrl-parse>
 </example>

 <example id='48'>
  <nl lang='en'> minnesota </nl>
  <nl lang='es'> minnesota </nl>
  <nl lang='ja'> minesota </nl>
  <nl lang='tr'> minnesota </nl>
  <nl lang='el'> minnesota </nl>
  <nl lang='de'> minnesota </nl>
  <nl lang='th'> มินเนโซตา </nl>
  <nl lang='zh'> 明尼苏达 </nl>
  <mrl lang='geo-funql'> ' mn ' </mrl>
  <mrl lang='geo-prolog'>  </mrl>
  <mrl-parse>
   <node id='0'> *n:StateAbbrev -> ({ ' mn ' }) </node>
  </mrl-parse>
 </example>

 <example id='49'>
  <nl lang='en'> new hampshire </nl>
  <nl lang='es'> new hampshire </nl>
  <nl lang='ja'> nyuu hanpushaa </nl>
  <nl lang='tr'> new hampshire </nl>
  <nl lang='el'> new hampshire </nl>
  <nl lang='de'> new hampshire </nl>
  <nl lang='th'> นิวแฮมพ์เชียร์ </nl>
  <nl lang='zh'> 新罕布什尔 </nl>
  <mrl lang='geo-funql'> ' new hampshire ' </mrl>
  <mrl lang='geo-prolog'>  </mrl>
  <mrl-parse>
   <node id='0'> *n:StateName -> ({ ' new hampshire ' }) </node>
  </mrl-parse>
 </example>

 <example id='50'>
  <nl lang='en'> riverside </nl>
  <nl lang='es'> riverside </nl>
  <nl lang='ja'> ribaasaido </nl>
  <nl lang='tr'> riverside </nl>
  <nl lang='el'> όχθη ποταμού </nl>
  <nl lang='de'> riverside </nl>
  <nl lang='th'> ริเวอร์ไซด์ </nl>
  <nl lang='zh'> 里弗赛德斯塔特 </nl>
  <mrl lang='geo-funql'> ' riverside ' </mrl>
  <mrl lang='geo-prolog'>  </mrl>
  <mrl-parse>
   <node id='0'> *n:CityName -> ({ ' riverside ' }) </node>
  </mrl-parse>
 </example>

 <example id='51'>
  <nl lang='en'> san francisco </nl>
  <nl lang='el'> san francisco </nl>
  <nl lang='de'> san francisco </nl>
  <nl lang='th'> ซานฟรานซิสโก </nl>
  <nl lang='zh'> 旧金山 </nl>
  <mrl lang='geo-funql'> ' san francisco ' </mrl>
  <mrl lang='geo-prolog'>  </mrl>
  <mrl-parse>
   <node id='0'> *n:CityName -> ({ ' san francisco ' }) </node>
  </mrl-parse>
 </example>

 <example id='52'>
  <nl lang='en'> south dakota </nl>
  <nl lang='es'> south dakota </nl>
  <nl lang='ja'> sausu dakota </nl>
  <nl lang='tr'> south dakota </nl>
  <nl lang='el'> νότια dakota </nl>
  <nl lang='el'> south dakota </nl>
  <nl lang='de'> sud dakota </nl>
  <nl lang='de'> south dakota </nl>
  <nl lang='th'> เซาท์ดาโกตา </nl>
  <nl lang='th'> เซาธ์ดาโกตา </nl>
  <nl lang='zh'> 南达科他 </nl>
  <mrl lang='geo-funql'> ' south dakota ' </mrl>
  <mrl lang='geo-prolog'>  </mrl>
  <mrl-parse>
   <node id='0'> *n:StateName -> ({ ' south dakota ' }) </node>
  </mrl-parse>
 </example>

 <example id='53'>
  <nl lang='en'> spokane </nl>
  <nl lang='es'> spokane </nl>
  <nl lang='ja'> supoken </nl>
  <nl lang='tr'> spokane </nl>
  <nl lang='el'> spokane </nl>
  <nl lang='de'> spokane </nl>
  <nl lang='th'> สโปเกน </nl>
  <nl lang='zh'> 斯波坎 </nl>
  <mrl lang='geo-funql'> ' spokane ' </mrl>
  <mrl lang='geo-prolog'>  </mrl>
  <mrl-parse>
   <node id='0'> *n:CityName -> ({ ' spokane ' }) </node>
  </mrl-parse>
 </example>

 <example id='54'>
  <nl lang='en'> washington </nl>
  <nl lang='es'> washington </nl>
  <nl lang='ja'> washinton </nl>
  <nl lang='tr'> washington </nl>
  <nl lang='el'> washington </nl>
  <nl lang='de'> washington </nl>
  <nl lang='th'> วอชิงตัน </nl>
  <nl lang='zh'> 华盛顿 </nl>
  <mrl lang='geo-funql'> ' wa ' </mrl>
  <mrl lang='geo-prolog'>  </mrl>
  <mrl-parse>
   <node id='0'> *n:StateAbbrev -> ({ ' wa ' }) </node>
  </mrl-parse>
 </example>

 <example id='55'>
  <nl lang='en'> georgia </nl>
  <nl lang='es'> georgia </nl>
  <nl lang='ja'> joojaa </nl>
  <nl lang='tr'> georgia </nl>
  <nl lang='el'> georgia </nl>
  <nl lang='de'> georgias </nl>
  <nl lang='de'> georgia </nl>
  <nl lang='th'> จอร์เจีย </nl>
  <nl lang='zh'> 佐治亚 </nl>
  <mrl lang='geo-funql'> ' georgia ' </mrl>
  <mrl lang='geo-prolog'>  </mrl>
  <mrl-parse>
   <node id='0'> *n:StateName -> ({ ' georgia ' }) </node>
  </mrl-parse>
 </example>

 <example id='56'>
  <nl lang='en'> wyoming </nl>
  <nl lang='es'> wyoming </nl>
  <nl lang='ja'> waiomingu </nl>
  <nl lang='tr'> wyoming </nl>
  <nl lang='el'> wyoming </nl>
  <nl lang='de'> wyoming </nl>
  <nl lang='de'> wyomings </nl>
  <nl lang='th'> ไวโอมิง </nl>
  <nl lang='zh'> 怀俄明 </nl>
  <mrl lang='geo-funql'> ' wyoming ' </mrl>
  <mrl lang='geo-prolog'>  </mrl>
  <mrl-parse>
   <node id='0'> *n:StateName -> ({ ' wyoming ' }) </node>
  </mrl-parse>
 </example>

 <example id='57'>
  <nl lang='en'> washington </nl>
  <nl lang='es'> washington </nl>
  <nl lang='ja'> washinton </nl>
  <nl lang='tr'> washington </nl>
  <nl lang='el'> washington </nl>
  <nl lang='de'> washington </nl>
  <nl lang='th'> วอชิงตัน </nl>
  <nl lang='zh'> 华盛顿 </nl>
  <mrl lang='geo-funql'> ' washington ' </mrl>
  <mrl lang='geo-prolog'>  </mrl>
  <mrl-parse>
   <node id='0'> *n:StateName -> ({ ' washington ' }) </node>
  </mrl-parse>
 </example>

 <example id='58'>
  <nl lang='en'> washington </nl>
  <nl lang='el'> washington </nl>
  <nl lang='de'> washington </nl>
  <nl lang='th'> วอชิงตัน </nl>
  <nl lang='zh'> 华盛顿 </nl>
  <mrl lang='geo-funql'> ' washington ' </mrl>
  <mrl lang='geo-prolog'>  </mrl>
  <mrl-parse>
   <node id='0'> *n:CityName -> ({ ' washington ' }) </node>
  </mrl-parse>
 </example>

 <example id='59'>
  <nl lang='en'> dc </nl>
  <nl lang='el'> dc </nl>
  <nl lang='de'> dc </nl>
  <nl lang='th'> ดีซี </nl>
  <nl lang='zh'> 特区 </nl>
  <mrl lang='geo-funql'> ' dc ' </mrl>
  <mrl lang='geo-prolog'>  </mrl>
  <mrl-parse>
   <node id='0'> *n:StateAbbrev -> ({ ' dc ' }) </node>
  </mrl-parse>
 </example>

 <example id='60'>
  <nl lang='en'> missouri </nl>
  <nl lang='el'> missouri </nl>
  <nl lang='de'> missouri </nl>
  <nl lang='th'> มิสซูรี </nl>
  <nl lang='zh'> 密苏里 </nl>
  <mrl lang='geo-funql'> ' missouri ' </mrl>
  <mrl lang='geo-prolog'>  </mrl>
  <mrl-parse>
   <node id='0'> *n:StateName -> ({ ' missouri ' }) </node>
  </mrl-parse>
 </example>

 <example id='61'>
  <nl lang='en'> idaho </nl>
  <nl lang='es'> idaho </nl>
  <nl lang='ja'> aidahou </nl>
  <nl lang='tr'> idaho </nl>
  <nl lang='el'> idaho </nl>
  <nl lang='de'> idaho </nl>
  <nl lang='th'> ไอดาโฮ </nl>
  <nl lang='zh'> 爱达荷 </nl>
  <mrl lang='geo-funql'> ' idaho ' </mrl>
  <mrl lang='geo-prolog'>  </mrl>
  <mrl-parse>
   <node id='0'> *n:StateName -> ({ ' idaho ' }) </node>
  </mrl-parse>
 </example>

 <example id='62'>
  <nl lang='en'> albany </nl>
  <nl lang='el'> albany </nl>
  <nl lang='de'> albany </nl>
  <nl lang='th'> อัลบานี </nl>
  <nl lang='zh'> 奥尔巴尼 </nl>
  <mrl lang='geo-funql'> ' albany ' </mrl>
  <mrl lang='geo-prolog'>  </mrl>
  <mrl-parse>
   <node id='0'> *n:CityName -> ({ ' albany ' }) </node>
  </mrl-parse>
 </example>

 <example id='63'>
  <nl lang='en'> red </nl>
  <nl lang='el'> red </nl>
  <nl lang='de'> red </nl>
  <nl lang='th'> เรด </nl>
  <nl lang='th'> เร็ด </nl>
  <nl lang='zh'> 红 </nl>
  <mrl lang='geo-funql'> ' red ' </mrl>
  <mrl lang='geo-prolog'>  </mrl>
  <mrl-parse>
   <node id='0'> *n:RiverName -> ({ ' red ' }) </node>
  </mrl-parse>
 </example>

 <example id='64'>
  <nl lang='en'> boston </nl>
  <nl lang='es'> boston </nl>
  <nl lang='ja'> bosuton </nl>
  <nl lang='tr'> boston </nl>
  <nl lang='el'> boston </nl>
  <nl lang='de'> boston </nl>
  <nl lang='th'> บอสตัน </nl>
  <nl lang='zh'> 波士顿 </nl>
  <mrl lang='geo-funql'> ' boston ' </mrl>
  <mrl lang='geo-prolog'>  </mrl>
  <mrl-parse>
   <node id='0'> *n:CityName -> ({ ' boston ' }) </node>
  </mrl-parse>
 </example>

 <example id='65'>
  <nl lang='en'> tennessee </nl>
  <nl lang='es'> tennessee </nl>
  <nl lang='ja'> teneshii </nl>
  <nl lang='tr'> tennessee </nl>